// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBghymTvuz7nSSNovPAwjeKF1W73Q6oXE',
    appId: '1:657096510394:android:017f59a43ea702693deb83',
    messagingSenderId: '657096510394',
    projectId: 'pc-api-6045211014556800621-787',
    storageBucket: 'pc-api-6045211014556800621-787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfyewtD8ic9SFSsZ4UiGGNWN5Sd25w6bE',
    appId: '1:657096510394:ios:34efc89c64eae8df3deb83',
    messagingSenderId: '657096510394',
    projectId: 'pc-api-6045211014556800621-787',
    storageBucket: 'pc-api-6045211014556800621-787.appspot.com',
    androidClientId: '657096510394-j3mpnd64fhga3gdnrp9ltj7tfh91a8h7.apps.googleusercontent.com',
    iosClientId: '657096510394-6b2ru121dmdkm4sg8vd1kv09oe9u47gm.apps.googleusercontent.com',
    iosBundleId: 'com.acar.hal.halApp',
  );
}
